### ISSUE TITLE
Capas de ruteo

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-07#5]
https://github.com/1022FSNSANCN02ARED/grupo-07/blob/381a665faa9b4b28931ebffb62c0fbd3bc7f9393/src/router/mainRouter.js#L7

probablemente las rutas, especialmente a medida que va a ir creciendo la app, mejor separarlas en grupos. Capaz un grupo para el user y otro para el producto es un buen lugar por dónde empezar, siguiendo la línea de lo hecho con las vistas.

**Comment by paoguzmanok** [comment]
División de rutas realizado.
